---
- name: User Creation
  hosts: all
  become: true
  gather_facts: false
  # vars:
  #   user_name: modi
  vars_file: user.yml
  tasks:
  - name: Create User {{ user_name }}
    user:
      name: "{{ user_name }}"
  - name: create a directory
    file:
      path: /opt/{{ user_name }}_temp_dir
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0755