---
- name: Creating a directory in the servers
  hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Creating a directory
    file:
      path: /home/ansadmin/testdir
      state: directory
      mode: 0755
      owner: ansadmin
